[project]
name = "clean-architecture-python"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pydantic-settings>=2.14.2",
    "uvicorn[standard]>=0.52.0",
]

[project.scripts]
cleanarchitecture-python = "clean_architecture_python.main:run"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]